const checkoutBase = "https://www.thekkc.net/pricing-plans/plan-customization";
const bookingFormUrl = "https://www.thekkc.net/booking-form?referral=booking_calendar_widget";
const plans = [
  ["First Timer Special", "$39", "3 classes · valid 14 days", `${checkoutBase}?planId=95589e75-4097-4581-bd41-b97a4bb1dff3&pricingVariantId=16e5871b-5040-445d-a5c9-37207e6155bf`],
  ["Starter", "$79/mo", "4 classes per month", `${checkoutBase}?planId=00882a68-7ca2-4cce-99d3-2fc61c53dd05&pricingVariantId=f70ac0f7-6632-4a74-b6fb-0783bb48362b`],
  ["Enthusiast", "$119/mo", "8 classes per month + merch savings", `${checkoutBase}?planId=3cbb67cc-c50e-42dc-9dfd-9deb693f812a&pricingVariantId=c769a879-d33a-4769-9b6b-aba11ebd5003`],
  ["Unlimited VIP", "$149/mo", "Unlimited classes + member events", `${checkoutBase}?planId=09435e6b-6126-47a4-abcb-389e99b1ec21&pricingVariantId=42ee0218-673f-4acf-a661-248a7f14bde3`],
];
export default function PassesPage() { return <main className="passes-page"><nav className="nav container"><a className="brand" href="/"><span>FEMME</span> KOLLECTIVE</a><a className="nav-cta" href="/#membership">Back to membership ↗</a></nav><section className="passes-hero container"><p className="eyebrow red"><i /> Packages + passes</p><h1>Choose your<br /><em>way in.</em></h1><p>Explore every Femme option, then continue to the secure Wix checkout or choose a class from the weekly timetable.</p></section><section className="passes-grid container">{plans.map(([name, price, detail, href]) => <a className="passes-card" href={href} target="_top" key={name}><small>FEMME PASS</small><h2>{name}</h2><strong>{price}</strong><p>{detail}</p><span>Continue to checkout →</span></a>)}<a className="passes-card pass-secondary" id="drop-in" href={bookingFormUrl} target="_top"><small>CASUAL PASS</small><h2>Drop-In</h2><strong>$30</strong><p>Pick a class on the live Wix timetable and pay during booking.</p><span>Choose a class →</span></a><a className="passes-card pass-secondary" id="three-class" href={bookingFormUrl} target="_top"><small>CLASS PACK</small><h2>3-Class Pack</h2><strong>$49</strong><p>Flexible visits without a monthly membership.</p><span>Choose a class →</span></a><a className="passes-card pass-secondary" id="six-class" href={bookingFormUrl} target="_top"><small>CLASS PACK</small><h2>6-Class Pack</h2><strong>$89</strong><p>More movement, more value.</p><span>Choose a class →</span></a></section></main> }
